# Setup
Import torch and check if there is a GPU available

In [1]:
import torch
print(torch.__version__)
# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("GPU is available")
else:
    device = torch.device('cpu')
    print("GPU is not available")

2.1.2
GPU is available


# Tensor Initialization

In [2]:
# Create a tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor)
print(my_tensor.dtype)
# Specify the type of the tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(my_tensor.dtype)
# Specify the device of the tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device = device)
print(my_tensor.device)
# Specify if the tensor requires gadient
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device = device, requires_grad=True)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.float32
cuda:0


In [3]:
# Other initialization methods
x = torch.empty(size = (3,3)) # The values will be random
print(x)
x = torch.zeros(size = (3,3))
print(x)
x = torch.rand(size = (3,3))
print(x)
x = torch.ones(size = (3,3))
print(x)
x = torch.eye(3,3) # Identity matrix
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)
x = torch.empty(size = (1,5)).normal_(mean=0, std=1)
print(x)
x = torch.empty(size = (1,5)).uniform_(0,1)
print(x)
x = torch.diag(torch.ones(3)) # This will create a diagonal matrix of 3x3
print(x)

tensor([[2.7554e+23, 2.7523e+23, 2.0319e-43],
        [0.0000e+00, 5.0932e+14, 4.4142e-41],
        [5.0932e+14, 4.4142e-41, 7.5551e+31]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5277, 0.3463, 0.3044],
        [0.6769, 0.9901, 0.5956],
        [0.2512, 0.8622, 0.8920]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.7974, -1.0475,  0.0801, -0.4518, -0.3537]])
tensor([[0.7613, 0.3044, 0.0398, 0.8131, 0.2974]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [4]:
 # How to initialize and convert tensors to other types (int, float, double)
tensor = torch.arange(4)
print(tensor)
print(tensor.dtype)
# Convert it to Bool
print(tensor.bool())
# Convert it to int16
print(tensor.short())
# Convert it to int64 **
print(tensor.long())
# Convert it to float16
print(tensor.half())
# Convert it to float32 **
print(tensor.float())
# Convert it to float64
print(tensor.double())

tensor([0, 1, 2, 3])
torch.int64
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


# Array-Tensor conversion

In [5]:
# Array to Tensor conversion
import numpy as np
np_array = np.zeros((5,5))
converted_tensor = torch.from_numpy(np_array)
print(converted_tensor)

# Tensor to Array conversion
converted_np_array = converted_tensor.numpy()
print(converted_np_array)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math

In [6]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
sum1 = torch.empty(3)
torch.add(x, y, out=sum1)
print('sum1:', sum1)
sum2 = torch.add(x,y)
print('sum2:', sum2)
sum3 = x + y
print('sum3:', sum3)

# Subtraction
sub = x - y
print('sub:', sub)

# Division
# element-wise
div1 = torch.true_divide(x, y)
print('div1:', div1)
# divide to an integer
div2 = torch.true_divide(x, 2)
print('div2:', div2)

sum1: tensor([10., 10., 10.])
sum2: tensor([10, 10, 10])
sum3: tensor([10, 10, 10])
sub: tensor([-8, -6, -4])
div1: tensor([0.1111, 0.2500, 0.4286])
div2: tensor([0.5000, 1.0000, 1.5000])


In [7]:
# Inplace Operations
t = torch.zeros(3)
print(t)
t.add_(x) # The "_" means that it is done inplace, so you dont need to do a copy of the tensor
print(t)
t += x
print(t)

tensor([0., 0., 0.])
tensor([1., 2., 3.])
tensor([2., 4., 6.])


In [8]:
# Element-wise exponentiation
print(x)
z = x.pow(2)
y = x ** 2
print(z)
print(y)

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([1, 4, 9])


In [9]:
# Matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(2)

tensor([[2.2288, 1.6781, 0.9315, 0.8727, 1.2683],
        [0.9671, 0.9370, 0.4855, 0.4906, 0.3887],
        [2.2041, 1.3339, 0.9488, 1.3817, 1.3416],
        [1.5571, 0.7693, 0.5542, 0.9183, 0.8736],
        [1.7653, 1.6380, 0.8403, 1.2146, 1.5484]])

In [10]:
# Simple Comparison
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [11]:
# Element-wise multiplication
print(x)
print(y)
z = x * y
print(z)

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([ 1,  8, 27])


In [12]:
# Matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2)  # 2x3
x4 = x1.mm(x2) # This is common to all pytorch functions
print(x3)
print(x4)

tensor([[1.0315, 0.9953, 0.9317],
        [1.3012, 1.0666, 0.9917]])
tensor([[1.0315, 0.9953, 0.9317],
        [1.3012, 1.0666, 0.9917]])


In [13]:
# dot product
z = torch.dot(x,y)
print(z)

tensor(36)


In [14]:
# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

In [15]:
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))  # will be expanded to 5x5
z1 = x1 - x2
z2 = x1 ** x2

# Useful Tensor Math Operations

In [16]:
# Sum columns (dim=0) or rows (dim=1)
sum_x = torch.sum(x, dim=0)

In [17]:
# Max and min values
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
z1 = torch.argmax(x, dim=0) # does the same as torch.max, but only returns the index
z2 = torch.argmin(x, dim=0)

In [18]:
# Absolute value
abs_x = torch.abs(x)

In [19]:
# Mean (the tensor needs to be float)
mean = torch.mean(x.float(), dim=0)

In [20]:
# Element-wise check if they are equal
z = torch.eq(x,y)

In [21]:
# Sort
sorted_y, indices = torch.sort(y, dim=0, descending=False)

In [22]:
# Limit the values of the tensor [0, 10]
z = torch.clamp(x, min=-5, max=5)
ReLU = torch.clamp(x, min=0)

In [23]:
# Check for True values
x = torch.tensor([1,0,1,1,1,0], dtype=bool)
z = torch.any(x)  # at least one True
print(z)
z = torch.all(x)  # all True
print(z)

tensor(True)
tensor(False)


# Tensor Indexing

In [24]:
batch_size = 10 # number of examples in a batch
features = 25
x = torch.rand((batch_size, features))

# Get the features of the first example
print(x[0].shape) #x[0] is equivalent to x[0,:]

# Get the first features of all of the example
print(x[:,0].shape)

# Get the first eight features of the third example in the batch
print(x[2, 0:8].shape)

torch.Size([25])
torch.Size([10])
torch.Size([8])


In [25]:
# Select values in a one-dimensional tensor
x = torch.arange(10)
indices = [2, 5, 8]
print(x)
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [26]:
# Select values in a two-dimensional tensor
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])

print(x)
print(x[rows, cols])  # This picks the second row and the fifth column, and then the first row and first colum

tensor([[0.5118, 0.4904, 0.3635, 0.2764, 0.0479],
        [0.8256, 0.0689, 0.4049, 0.5070, 0.5606],
        [0.1545, 0.1587, 0.9935, 0.7983, 0.7989]])
tensor([0.5606, 0.5118])


In [27]:
# Conditional indexing
x = torch.arange(10)
print(x)

print(x[(x<2)|(x>8)])
print(x[(x<6)&(x>3)])

print(x[x.remainder(2) == 0]) # Even numbers

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([4, 5])
tensor([0, 2, 4, 6, 8])


## Useful Operations

In [28]:
# Change the values of the tensor
print(torch.where(x > 5, x*1, x*0)) # when x > 5 -> x, when x =< 5 -> 0

tensor([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])


In [29]:
# Check for unique values
x = torch.tensor([0,0,1,2,2,3,4])
print(x.unique())

tensor([0, 1, 2, 3, 4])


In [30]:
# Number of dimentions of a tensor
x1 = torch.tensor([0,0,0])
x2 = torch.tensor([[0,0,0],[0,0,0]])
x3 = torch.tensor([[[0,0,0],[0,0,0],[0,0,0]]])
print(x1.ndimension())
print(x2.ndimension())
print(x3.ndimension())

1
2
3


In [31]:
# Count the number of elements in a tensor
print(x1.numel())
print(x2.numel())
print(x3.numel())

3
6
9


# Tensor Reshaping Dimensions

In [32]:
# Change a 9 element vector to a 3x3 matrix
x = torch.arange(9)
print(x.shape)

x_3x3_1 = x.view(3,3)
x_3x3_2 = x.reshape(3,3)  # Reshape is the prefered choice

print(x_3x3_1.shape)
print(x_3x3_2.shape)

torch.Size([9])
torch.Size([3, 3])
torch.Size([3, 3])


In [33]:
# Concatenate tensors
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
z = torch.cat((x1,x2), dim=0)
print(z.shape)

torch.Size([4, 5])


In [34]:
# Matrix to vector
z = x1.view(-1)
print(z.shape)
z = x1.reshape(-1)
print(z.shape)

torch.Size([10])
torch.Size([10])


In [35]:
# Transpose
x = torch.arange(9)
x = x.reshape((3,3))
print(x)
print(x.t())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [36]:
# Permute (Similar to transpose, but used for more dimensions)
batch = 64
x = torch.rand((batch, 2, 5))
print(x.shape)

z1 = x.view(batch, -1) # adjust automatically the rest of the dimentions
print(z1.shape)

z2 = x.permute(0, 2, 1) # the ordering of the dimentions is (first, third, second), so batch stays the same
print(z2.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])
torch.Size([64, 5, 2])


In [37]:
# Row-Column vector transformation
x = torch.arange(10)
print(x.shape)

row = x.unsqueeze(0)
print(row.shape)

col = x.unsqueeze(1)
print(col.shape)

z = x.unsqueeze(0).unsqueeze(1)
print(z.shape)

torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
