<a href="https://colab.research.google.com/github/Juliandlb/Deep-Learning-with-Pytorch/blob/main/Introduction%20to%20Tensors/Introduction_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup
Import torch and check if there is a GPU available

In [2]:
import torch
print(torch.__version__)
# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("GPU is available")
else:
    device = torch.device('cpu')
    print("GPU is not available")

2.3.1+cu121
GPU is available


# Tensor Initialization

In [3]:
# Create a tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor)
print(my_tensor.dtype)
# Specify the type of the tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(my_tensor.dtype)
# Specify the device of the tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device = device)
print(my_tensor.device)
# Specify if the tensor requires gadient
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device = device, requires_grad=True)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.float32
cuda:0


In [4]:
# Other initialization methods
x = torch.empty(size = (3,3)) # The values will be random
print(x)
x = torch.zeros(size = (3,3))
print(x)
x = torch.rand(size = (3,3))
print(x)
x = torch.ones(size = (3,3))
print(x)
x = torch.eye(3,3) # Identity matrix
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)
x = torch.empty(size = (1,5)).normal_(mean=0, std=1)
print(x)
x = torch.empty(size = (1,5)).uniform_(0,1)
print(x)
x = torch.diag(torch.ones(3)) # This will create a diagonal matrix of 3x3
print(x)

tensor([[-3.9807e+01,  0.0000e+00,  1.8077e-43],
        [ 0.0000e+00, -7.9118e-38,  3.1183e-41],
        [-3.9233e-13,  4.4232e-41,  5.1839e-21]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6851, 0.0228, 0.9030],
        [0.8742, 0.3095, 0.2950],
        [0.8248, 0.4667, 0.6026]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.7720,  0.0359, -0.7883, -0.4633,  0.3718]])
tensor([[0.7452, 0.7901, 0.8594, 0.1791, 0.9098]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [5]:
 # How to initialize and convert tensors to other types (int, float, double)
tensor = torch.arange(4)
print(tensor)
print(tensor.dtype)
# Convert it to Bool
print(tensor.bool())
# Convert it to int16
print(tensor.short())
# Convert it to int64 **
print(tensor.long())
# Convert it to float16
print(tensor.half())
# Convert it to float32 **
print(tensor.float())
# Convert it to float64
print(tensor.double())

tensor([0, 1, 2, 3])
torch.int64
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


# Array-Tensor conversion

In [6]:
# Array to Tensor conversion
import numpy as np
np_array = np.zeros((5,5))
converted_tensor = torch.from_numpy(np_array)
print(converted_tensor)

# Tensor to Array conversion
converted_np_array = converted_tensor.numpy()
print(converted_np_array)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math

In [7]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
sum1 = torch.empty(3)
torch.add(x, y, out=sum1)
print('sum1:', sum1)
sum2 = torch.add(x,y)
print('sum2:', sum2)
sum3 = x + y
print('sum3:', sum3)

# Subtraction
sub = x - y
print('sub:', sub)

# Division
# element-wise
div1 = torch.true_divide(x, y)
print('div1:', div1)
# divide to an integer
div2 = torch.true_divide(x, 2)
print('div2:', div2)

sum1: tensor([10., 10., 10.])
sum2: tensor([10, 10, 10])
sum3: tensor([10, 10, 10])
sub: tensor([-8, -6, -4])
div1: tensor([0.1111, 0.2500, 0.4286])
div2: tensor([0.5000, 1.0000, 1.5000])


In [19]:
# Inplace Operations
t = torch.zeros(3)
print(t)
t.add_(x) # The "_" means that it is done inplace, so you dont need to do a copy of the tensor
print(t)
t += x
print(t)

tensor([0., 0., 0.])
tensor([1., 2., 3.])
tensor([2., 4., 6.])


In [44]:
# Element-wise exponentiation
print(x)
z = x.pow(2)
y = x ** 2
print(z)
print(y)

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([1, 4, 9])


In [45]:
# Matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(2)

tensor([[2.0930, 2.1385, 1.3010, 2.5661, 1.4291],
        [1.8427, 1.6956, 0.8098, 2.0217, 1.0958],
        [2.2011, 1.7429, 0.7727, 1.8268, 0.9833],
        [1.3485, 1.4166, 0.9421, 1.4241, 0.4745],
        [2.2547, 2.2016, 1.3909, 2.0209, 1.0089]])

In [23]:
# Simple Comparison
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [49]:
# Element-wise multiplication
print(x)
print(y)
z = x * y
print(z)

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([ 1,  8, 27])


In [50]:
# Matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2)  # 2x3
x4 = x1.mm(x2) # This is common to all pytorch functions
print(x3)
print(x4)

tensor([[1.1151, 1.6350, 1.2353],
        [0.5434, 0.8848, 1.1452]])
tensor([[1.1151, 1.6350, 1.2353],
        [0.5434, 0.8848, 1.1452]])


In [51]:
# dot product
z = torch.dot(x,y)
print(z)

tensor(36)


In [54]:
# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

In [56]:
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))  # will be expanded to 5x5
z1 = x1 - x2
z2 = x1 ** x2

# Useful Tensor Math Operations

In [68]:
# Sum columns (dim=0) or rows (dim=1)
sum_x = torch.sum(x, dim=0)

In [76]:
# Max and min values
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
z1 = torch.argmax(x, dim=0) # does the same as torch.max, but only returns the index
z2 = torch.argmin(x, dim=0)

In [70]:
# Absolute value
abs_x = torch.abs(x)

In [77]:
# Mean (the tensor needs to be float)
mean = torch.mean(x.float(), dim=0)

In [81]:
# Element-wise check if they are equal
z = torch.eq(x,y)

In [85]:
# Sort
sorted_y, indices = torch.sort(y, dim=0, descending=False)

In [87]:
# Limit the values of the tensor [0, 10]
z = torch.clamp(x, min=-5, max=5)
ReLU = torch.clamp(x, min=0)

In [92]:
# Check for True values
x = torch.tensor([1,0,1,1,1,0], dtype=bool)
z = torch.any(x)  # at least one True
print(z)
z = torch.all(x)  # all True
print(z)

tensor(True)
tensor(False)


# Tensor Indexing